#==========================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#
# https://github.com/KFERMercer/OpenWrt-CI
#
# https://github.com/1orz/My-action
#
# https://github.com/garypang13/Actions-OpenWrt-Nginx
#
#==========================================================

name: Openwrt_Generic_Firmware_Compile

on:
  # release:
  #   types: [published]
  watch:
    types: [started]
  schedule:
    - cron: 00 10 * * 6

env:
  TARGET: Openwrt_Generic_Firmware
  REPO_URL: https://github.com/coolsnowwolf/lede
  # REPO_URL: https://github.com/u0225/lede
  ### -+-+-
  REPO_BRANCH: master
  # REPO_BRANCH: r8.1.12
  # REPO_BRANCH: r9.8.17
  # REPO_BRANCH: r9.10.10
  # REPO_BRANCH: 20200408
  # REPO_BRANCH: 20200416
  # REPO_BRANCH: r20.5.20
  ### -+-+-
  # CPU_M: x86_32
  CPU_M: x86_64
  # CPU_M: arm_ar71xx
  # CPU_M: arm_mt7620
  # CONFIG_M: default
  # CONFIG_M: full
  # CONFIG_M: lite
  CONFIG_M: mini_lite
  VPS_S: SSRPlus
  # VPS_S: SSRPlus_new
  # VPS_S: PSW
  # COMPILE_M: 
  ### -+-+-
  BRANCH_SET: armt/master.sh
  # BRANCH_SET: armt/r89.sh
  # BRANCH_SET: armt/r20.sh
  ### -+-+-
  ### -+-+-
  # VPS_M: vps/arm.ssr
  # VPS_M: vps/arm.psw
  # VPS_M: vps/x86.ssr
  # VPS_M: vps/x86.psw
  ### -+-+-
  CONFIG_FILE: config/.config
  FEEDS_FILE: feeds.default
  ARM_SET: armt/armt-set.sh
  X86_DIY: diy/diy.sh
  FREE_UP_DISK: true
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  TZ: Asia/Shanghai

jobs:
  build_openwrt:
    name: Build OpenWrt
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-18.04
    # runs-on: ubuntu-16.04

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget
          # sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          curl -fsSL https://raw.githubusercontent.com/u0225/openwrt_lede_actions/master/.bashrc >> ~/.bashrc
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          df -h

      - name: Set date
        id: date
        run: |
          echo "::set-env name=date::$(date +'%Y-%m-%d')"
          echo "::set-env name=date1::$(date +'%y%m%d')"
          echo "::set-env name=date2::$(date +'%Y-%m-%d_%H.%M')"
          echo "::set-env name=date3::$(date +'%Y-%m-%d_%H.%M.%S')"
          chmod -R 775 ./

      - name: Set vps_m
        id: vps_m
        run: |
          for v in SSRPlus SSRPlus_new PSW
          do
            if [ ${{ env.VPS_S }} == '$v' ];then
            echo "::set-env name=vps_m::$(echo 'cat vps/$v >> openwrt/.config')"
            fi
          done

      - name: Clone openwrt
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
          chmod -R 775 ./
          cp ./${{ env.FEEDS_FILE }} openwrt/feeds.conf.default
          ./diy/others.sh
          ./$BRANCH_SET

      - name: Free up disk space
        if: env.FREE_UP_DISK == 'true'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo mkdir -p -m 777 openwrt/build_dir /mnt/openwrt/dl /mnt/openwrt/staging_dir /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/build_dir/host
          ln -s /mnt/openwrt/build_dir/hostpkg openwrt/build_dir/hostpkg
          ln -s /mnt/openwrt/build_dir/host openwrt/build_dir/host
          ln -s /mnt/openwrt/dl openwrt/dl
          ln -s /mnt/openwrt/staging_dir openwrt/staging_dir
          df -h

      - name: Git pull Update feeds and install
        run: |
          cd openwrt
          git pull
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          df -h

      - name: Load custom configuration
        run: |
          rm -f openwrt/.config*
          touch openwrt/.config
          cat diy/x32 >> openwrt/.config
          # cat diy/Setting >> openwrt/.config
          cat diy/drive >> openwrt/.config
          # cat diy/luci-app >> openwrt/.config
          cat diy/mini-lite >> openwrt/.config
          cat diy/samba4 >> openwrt/.config
          # cat diy/samba36 >> openwrt/.config
          # cat diy/mwan3 >> openwrt/.config
          # cat ${{ env.VPS_M }} >> openwrt/.config
          ${{ env.vps_m }}
          # ${{ env.psw }}
          # ${{ env.ssrplus }}
          # ${{ env.ssrplus_new }}
          cd openwrt
          ../$X86_DIY
          ./scripts/feeds install -a
          make defconfig

      - name: Make download
        run: |
          cd openwrt
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
          df -h

      - name: Compile firmware
        run: |
          cd openwrt
          echo -e "$(($(nproc)+1)) thread compile"
          make -j$(($(nproc)+1)) || make -j1 V=s
          # make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin
          echo "::set-env name=status::success"

      # - name: Upload entire bin directory
      #   uses: actions/upload-artifact@master
      #   if: always()
      #   with:
      #     name: ${{ env.date1 }}_${{ env.TARGET }}_${{ env.REPO_BRANCH }}_${{ env.VPS_S }}_bin_all
      #     path: openwrt/bin

      - name: Prepare ipk packages artifact
        run: mkdir ./ipk && mkdir ./ipk/targets && cp -r ./openwrt/bin/targets/*/*/packages ./ipk/targets/packages && cp -r ./openwrt/bin/packages ./ipk

      - name: Upload ipk packages artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.date }}_${{ env.TARGET }}_${{ env.REPO_BRANCH }}_${{ env.VPS_S }}_ipk
          path: ./ipk

      # - name: Prepare artifact
      #   run: find openwrt/bin/targets/ -type d -name "packages" | xargs rm -rf {}

      # - name: Upload artifact
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: ${{ env.date1 }}_${{ env.TARGET }}_${{ env.REPO_BRANCH }}_${{ env.VPS_S }}_firmware_all
      #     path: openwrt/bin/targets/

      - name: Organize files
        id: organize
        if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
        run: |
          mkdir firmware && find openwrt/bin/targets/*/*/* -maxdepth 0 -name "*uefi-gpt*" -or -name "*combined*" -or -name "*.vmdk" -or -name "*vmlinuz" -or -name "*.seed" -or -name "*.manifest" -or -name "sha256sums" | xargs -i mv -f {} ./firmware/
          cp openwrt/.config ./firmware/${{ env.date1 }}_${{ env.TARGET }}_${{ env.REPO_BRANCH }}_${{ env.VPS_S }}.config
          cd firmware
          echo "::set-env name=FIRMWARE::$PWD"
          echo "::set-output name=status::success"

      - name: Prepare Upload firmware artifact
        uses: actions/upload-artifact@master
        if: steps.organize.outputs.status == 'success' && !cancelled()
        with:
          name: ${{ env.date }}_${{ env.TARGET }}_${{ env.REPO_BRANCH }}_${{ env.VPS_S }}_firmware
          path: ${{ env.FIRMWARE }}
