#==========================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#
# https://github.com/KFERMercer/OpenWrt-CI
#
# https://github.com/1orz/My-action
#
# https://github.com/garypang13/Actions-OpenWrt-Nginx
#
#==========================================================

name: OpenWrt_tl-wdr3320-v2-16m_firmware

on:
  watch:
    types: [started]
  schedule:
    - cron: 00 10 * * 6

env:
  TARGET: Openwrt_tl-wdr3320-v2-16m
  # REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_URL: https://github.com/u0225/lede
  # REPO_BRANCH: master
  REPO_BRANCH: r8.1.12
  # REPO_BRANCH: r9.8.17
  # REPO_BRANCH: r9.10.10
  # REPO_BRANCH: 20200408
  # REPO_BRANCH: 20200416
  # REPO_BRANCH: r20.5.20
  CONFIG_FILE: config/.config
  FEEDS_FILE: feeds.default
  # VPS_S: 2SRPlus
  VPS_S: PSW
  # VPS_ARM_M: vps/arm.ssr
  VPS_ARM_M: vps/arm.psw
  # VPS_ARM_M: vps/arm-full-32m.ssr
  # VPS_ARM_M: vps/arm-full-32m.psw
  # VPS_X86_M: vps/x86.ssr
  # VPS_X86_M: vps/x86.psw
  BRANCH_SET: armt/r89.sh
  # BRANCH_SET: armt/r20.sh
  # BRANCH_SET: armt/master.sh
  ARM_SET: armt/armt-set.sh
  X86_DIY: diy/diy.sh
  FREE_UP_DISK: true
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  TZ: Asia/Shanghai

jobs:
  build_openwrt:
    name: Build OpenWrt
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-18.04
    # runs-on: ubuntu-16.04

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget
          # sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint
          # sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          curl -fsSL https://raw.githubusercontent.com/u0225/openwrt_lede_actions/master/.bashrc >> ~/.bashrc
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          df -h

      - name: Clone openwrt
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH lede
          chmod -R 775 ./
          cd lede
          cp ../${{ env.FEEDS_FILE }} feeds.conf.default
          ../$BRANCH_SET
          chmod -R 775 ../

      - name: Free up disk space
        if: env.FREE_UP_DISK == 'true'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo mkdir -p -m 777 lede/build_dir /mnt/lede/dl /mnt/lede/staging_dir /mnt/lede/build_dir/hostpkg /mnt/lede/build_dir/host
          ln -s /mnt/lede/build_dir/hostpkg lede/build_dir/hostpkg
          ln -s /mnt/lede/build_dir/host lede/build_dir/host
          ln -s /mnt/lede/dl lede/dl
          ln -s /mnt/lede/staging_dir lede/staging_dir
          df -h

      - name: Git pull Update feeds and install
        run: |
          cd lede
          # git pull
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          df -h

      - name: Load custom configuration
        run: |
          rm -f lede/.config*
          touch lede/.config
          cat armt/wdr3320-16m >> lede/.config
          cat armt/armt-luci-app-16m >> lede/.config
          cat ${{ env.VPS_ARM_M }} >> lede/.config
          cd lede
          ../$ARM_SET
          ./scripts/feeds install -a
          make defconfig

      - name: Make download
        run: |
          cd lede
          make download -j8
          find ./dl/ -size -1024c -exec rm -f {} \;
          df -h

      - name: Compile firmware
        run: |
          cd lede
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Get current date
        id: date
        run: |
          echo "::set-env name=date::$(date +'%Y-%m-%d')"
          echo "::set-env name=date1::$(date +'%y%m%d')"
          echo "::set-env name=date2::$(date +'%Y-%m-%d_%H.%M')"
          echo "::set-env name=date3::$(date +'%Y-%m-%d_%H.%M.%S')"

      - name: Prepare ipk packages artifact
        run: mkdir ./ipk && mkdir ./ipk/targets && cp -r ./lede/bin/targets/*/*/packages ./ipk/targets/packages && cp -r ./lede/bin/packages ./ipk

      - name: Upload ipk packages artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.TARGET }}_${{ env.REPO_BRANCH }}_${{ env.VPS_S }}_ipk_packages_${{ env.date }}
          path: ./ipk

      - name: Prepare artifact
        run: |
          cp lede/.config ./lede/bin/targets/${{ env.TARGET }}_${{ env.REPO_BRANCH }}_${{ env.VPS_S }}_${{ env.date1 }}.config
          find lede/bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.TARGET }}_${{ env.REPO_BRANCH }}_${{ env.VPS_S }}_firmware_${{ env.date }}
          path: lede/bin/targets/
